### ISSUE TITLE
AsyncEffectShootout with MacrotaskExecutor

### ISSUE THREAD

**Issue by armanbilge** [japgolly/scalajs-benchmark#217]
Follow-up to #206: would be interesting to run the `AsyncEffectShootout` with the new `MacrotaskExecutor` just released:
https://github.com/scala-js/scala-js-macrotask-executor

This is the polyfill mentioned in https://github.com/japgolly/scalajs-benchmark/issues/203#issuecomment-899177982. Should level the playing field for CE3 hopefully 😅 

Not sure how straightforward it is to swap out the executor for the various effect implementations 🤔

**Comment by japgolly** [comment]
Noice! Probably just a matter of upgrading to CE 3.2.8 once it's out

**Comment by armanbilge** [comment]
Ahh, sorry I didn't explain the change clearly. This code was already inside of CE3, we extracted it out into a seperate lib so _everyone_ can use it :)

**Comment by japgolly** [comment]
Ah right. I've just updated the online demos now to use CE 3.2.7 but the results are still the same as before :(
https://japgolly.github.io/scalajs-benchmark/res/scala-2.13.6-sjs-1.7.0.html#/shootouts/async_effects

**Comment by armanbilge** [comment]
Right, the change that needs to happen would be using this `MacrotaskExecutor `for all the other effect types. CE is already using it. Which is why it's possibly non-trivial 😅

**Comment by armanbilge** [comment]
As of Scala.js 1.8.0 the `MacrotaskExecutor` is now officially recommended:
https://www.scala-js.org/news/2021/12/10/announcing-scalajs-1.8.0/
