### ISSUE TITLE
Use standard high-resolution timer in browsers

### ISSUE THREAD

**Issue by ochrons** [japgolly/scalajs-benchmark#6]
http://www.w3.org/TR/hr-time/#sec-DOMHighResTimeStamp

http://caniuse.com/#feat=high-resolution-time

`window.performance.now();`

**Comment by japgolly** [comment]
Ah yeah, that's already in use - it just doesn't look like it.

The default timer is chosen here:
https://github.com/japgolly/scalajs-benchmark/blob/master/benchmark/src/main/scala/japgolly/scalajs/benchmark/engine/Clock.scala#L78-L79

Which points to `SysNano` which uses `System.nanoTime`
https://github.com/japgolly/scalajs-benchmark/blob/master/benchmark/src/main/scala/japgolly/scalajs/benchmark/engine/Clock.scala#L32

Which Scala.JS implements by checking if `window.performance.now` is available:
https://github.com/scala-js/scala-js/blob/e51625a62faf464f5a68fdc97e6670757c3971c9/javalanglib/src/main/scala/java/lang/System.scala#L27-L45

**Comment by ochrons** [comment]
Ah, ok, the Chrome specific timer threw me off course :)


On Sat, Nov 28, 2015 at 3:36 AM, David Barri <notifications@github.com>
wrote:

> Ah yeah, that's already in use - it just doesn't look like it.
>
> The default timer is chosen here:
>
> https://github.com/japgolly/scalajs-benchmark/blob/master/benchmark/src/main/scala/japgolly/scalajs/benchmark/engine/Clock.scala#L78-L79
>
> Which points to SysNano which uses System.nanoTime
>
> https://github.com/japgolly/scalajs-benchmark/blob/master/benchmark/src/main/scala/japgolly/scalajs/benchmark/engine/Clock.scala#L32
>
> Which Scala.JS implements by checking if window.performance.now is
> available:
>
> https://github.com/scala-js/scala-js/blob/e51625a62faf464f5a68fdc97e6670757c3971c9/javalanglib/src/main/scala/java/lang/System.scala#L27-L45
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/japgolly/scalajs-benchmark/issues/6#issuecomment-160236203>
> .
>



-- 
Otto Chrons - otto@chrons.me
tel/whatsapp/telegram/wechat: +358 50 359 1401
skype: ochrons

**Comment by japgolly** [comment]
Understandably :)
Chrome has a higher precision time that you can access if you start it with `--enable-benchmarking` which is why it gets first priority if available.
