### ISSUE TITLE
Ability to export results into JSON representation of JMH format wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [japgolly/scalajs-benchmark#68]
Use cases:
1) plotting with external tools like [jmh-visualizer](https://github.com/jzillmann/jmh-visualizer)
2) importing results into [benchdb](https://github.com/lightbend/benchdb)

**Comment by japgolly** [comment]
Very cool. I didn't even know JMH could output JSON!

**Comment by japgolly** [comment]
v0.6.0 on its way to maven central with support for this. Thanks for the good idea!

**Comment by plokhotnyuk** [comment]
David, thank you so much!

I'm going to extend [JMH benchmarks for jsoniter-scala](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark) to run with Scala.js using your library.

I have been already faced that [warm-up iteration should be split from from the main measuring](https://github.com/oracle/graal/issues/2452). And now wondering if it would be possible to reuse this library for testing with Node.js (the original or from the GraalVM installation).
