### ISSUE TITLE
Unexpected linker error with JDK 8

### ISSUE THREAD

**Issue by plokhotnyuk** [japgolly/scalajs-benchmark#87]
I'm trying to use the Scala.js benchmark in this PR: https://github.com/plokhotnyuk/jsoniter-scala/pull/526

Currently, build `sbt jsoniter-scala-benchmarkJS/fullOptJS` fails with the following error:
```
[error] java.nio.file.FileSystemLoopException: /META-INF/resources/webjars/jstat/1.9.3
[error]         at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:294)
[error]         at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
[error]         at java.nio.file.Files.walkFileTree(Files.java:2706)
[error]         at org.scalajs.linker.PathIRContainer$.org$scalajs$linker$PathIRContainer$$walkIR(PathIRContainer.scala:95)
[error]         at org.scalajs.linker.PathIRContainer$JarIRContainer.$anonfun$sjsirFiles$2(PathIRContainer.scala:67)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
[error]         at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313)
[error]         at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
[error]         at scala.concurrent.package$.blocking(package.scala:146)
[error]         at org.scalajs.linker.PathIRContainer$JarIRContainer.$anonfun$sjsirFiles$1(PathIRContainer.scala:59)
[error]         at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error]         at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error]         at scala.util.Success.map(Try.scala:213)
[error]         at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error]         at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error]         at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error]         at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error]         at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[error]         at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[error]         at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[error]         at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[error]         at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[error] (jsoniter-scala-benchmarkJS / Compile / scalaJSIR) java.nio.file.FileSystemLoopException: /META-INF/resources/webjars/jstat/1.9.3
```
All is fine when JDK 11+ is used:
```
sbt -java-home /usr/lib/jvm/openjdk-15 jsoniter-scala-benchmarkJS/fullOptJS
```

**Comment by japgolly** [comment]
What version of Scala.JS and what version of Java are you using?

Also if it's Scala. JS 1.x have you added `.enablePlugin(JsDependencies)`
to SBT?

**Comment by plokhotnyuk** [comment]
Hi, David!

Thanks for fast response!

I use Amazon Correto 8/11 and Open JDK 15 locally or Zulu 8/11/15 on Github Actions CI or Oracle JDK 8/11 on Travis CI.

Yes, the `JsDependencies` plugin is added.

Full changes are in the PR mentioned above.

**Comment by japgolly** [comment]
Ah, probably you're having the same problem I had on scalajs-react. Scala.JS 1.0 and Java 8 have an issue handling certain webjars. For scalajs-react's CI, I changed the config to test Java 8 with Scala.JS 0.6 and Java 11 with Scala.JS 1.0 and it successfully avoided this problem. See here: https://github.com/scala-js/scala-js/issues/4031

**Comment by plokhotnyuk** [comment]
Thank you a lot, David!

Closing it here as related to the Scala.js repo.

**Comment by japgolly** [comment]
No worries! Glad it helped. :peace_symbol:

**Comment by plokhotnyuk** [comment]
David, can this affected dependency be safely excluded? Is it required or optional?

I've tried `libraryDependencies += "com.github.japgolly.scalajs-benchmark" %%% "benchmark" % "0.6.0" exclude ("org.webjars.npm", "jstat"),` but it doesn't work.

**Comment by japgolly** [comment]
`"jstat"` is mandatory as it's got all the complex math in it to help calculate the error scores.

Maybe scala-js team will know some better workarounds (?)

**Comment by plokhotnyuk** [comment]
I would not overestimate statistics which based on normal distribution for the benchmark scores. In most cases it is misleading because behavior of them is nonlinear. Even JMH Visualizer doesn't use error scores that calculated by JMH tool when displaying error range.

**Comment by japgolly** [comment]
We don't use the normal distribution, both JMH and scalajs-benchmark use a T-distribution.

**Comment by plokhotnyuk** [comment]
[Here](https://plokhotnyuk.github.io/jsoniter-scala/openjdk-15.json) is a JSON sample of JMH tool ouptut. Please see the `scoreConfidence` values are always much lower and greater than min and max `rawData` values correspondingly. So in my case they are misleading mostly.

**Comment by japgolly** [comment]
I think it's telling you something important though: you've made the settings to small to be appropriate for what you're testing - that's why the error is so large: your results aren't very accurate. It's fine when there's a big gap in what you're comparing but if you then later try to make incremental smaller changes the BM is going to be too noisy to be trustworthy.

Here's a sample of some results of mine with the default settings (i.e. 5 forks x (5 + 5) x 10s)

```json
[
    {
        "jmhVersion" : "1.21",
        "benchmark" : "shipreq.benchmark.ApplyEventBM.trusted",
        "mode" : "avgt",
        "threads" : 1,
        "forks" : 5,
        "jvm" : "/usr/lib/jvm/java-11-graalvm/bin/java",
        "jvmArgs" : [
            "-XX:+UnlockExperimentalVMOptions",
            "-XX:+EnableJVMCIProduct",
            "-XX:-UnlockExperimentalVMOptions",
            "-XX:ThreadPriorityPolicy=1"
        ],
        "jdkVersion" : "11.0.6",
        "vmName" : "OpenJDK 64-Bit Server VM",
        "vmVersion" : "11.0.6+9-jvmci-20.0-b02",
        "warmupIterations" : 5,
        "warmupTime" : "10 s",
        "warmupBatchSize" : 1,
        "measurementIterations" : 5,
        "measurementTime" : "10 s",
        "measurementBatchSize" : 1,
        "params" : {
            "events" : "1000",
            "type" : "full"
        },
        "primaryMetric" : {
            "score" : 13.899191764501177,
            "scoreError" : 0.16536310020186387,
            "scoreConfidence" : [
                13.733828664299313,
                14.064554864703041
            ],
            "scorePercentiles" : {
                "0.0" : 13.483149173854448,
                "50.0" : 13.93208077437326,
                "90.0" : 14.125172217231638,
                "95.0" : 14.199357382307062,
                "99.0" : 14.230904106685633,
                "99.9" : 14.230904106685633,
                "99.99" : 14.230904106685633,
                "99.999" : 14.230904106685633,
                "99.9999" : 14.230904106685633,
                "100.0" : 14.230904106685633
            },
            "scoreUnit" : "ms/op",
            "rawData" : [
                [
                    13.50123289608637,
                    13.562181406504065,
                    13.532597077131259,
                    13.509768663967611,
                    13.483149173854448
                ],
                [
                    14.230904106685633,
                    14.124788122881355,
                    14.080898909985935,
                    14.07121788607595,
                    14.125748358757063
                ],
                [
                    13.954460927475592,
                    14.009455102240896,
                    13.903789906944445,
                    13.902306091666667,
                    13.93208077437326
                ],
                [
                    13.86481111495845,
                    13.857893156509695,
                    13.879303542302358,
                    13.820965359116022,
                    13.83399596957123
                ],
                [
                    14.107257973201692,
                    14.082638419127989,
                    14.046322970505617,
                    14.018424542016806,
                    14.04360166058906
                ]
            ]
        },

```

**Comment by plokhotnyuk** [comment]
You have shown a great example of multi-mode behavior of GraalVM and for this case just displaying `T` and `⊥` range for confidence scores hiding that too. A better option would be displaying all values in the chart bar using alpha channel or using some another way to visualize all samples an their modalities in different forks.

**Comment by japgolly** [comment]
Sorry I don't quite know what you mean. To summarise, I think the error scores are fine and regardless of what I think, following JMH is the smart thing to do. I think you should be increasing you JMH BM times but maybe I'm missing your point.

Anyway, I won't be touching the graph in scalajs-benchmark until 1.0 at some point in the future -- not enough time :( PRs welcome though.
