### ISSUE TITLE
Switch to ops/s as the main score metric in JMH JSON wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [japgolly/scalajs-benchmark#89]
It will be easier to compare winners on charts.

Please, consider making throughput scores (ops/s) as default.

**Comment by japgolly** [comment]
Sorry but I disagree. Most of what I've seen (and my own personal preferences) is average time.

However you shouldn't be constrained by my preferences and in the coming ver 0.7.0 you'll be able to set ops/s as the main yourself via config. If you're super keen you can already do it with the master branch. It's the `formatResults` field in `GuiOptions`.

**Comment by plokhotnyuk** [comment]
Thanks for your great work!

The configuration option will be more than enough for me.

Closing the issue and waiting for the upcoming release with impatience...

**Comment by japgolly** [comment]
I did some refactoring today, renaming classes so that they're clearer and it's highlighted to me that what I told you above isn't true (!). `SuiteResultsFormat`s are configurable (JMH JSON vs CSV) but `BmResultFormat`s are *not*. Better fix that.....

**Comment by japgolly** [comment]
Ok fixed this now. So @plokhotnyuk you'll probably want to use this when 0.7.0 is released:

```scala
GuiOptions.default.copy(
  bmResultFormats = ctx => Vector(BmResultFormat.OpsPerSec, BmResultFormat.chooseTimePerOp(ctx))
  )
```

If you want 3 decimal places, change `BmResultFormat.OpsPerSec` to `BmResultFormat.OpsPerSec3`. Or you can make/specify your own format.
