### ISSUE TITLE
Wrong conversion to hours and days

### ISSUE THREAD

**Issue by plokhotnyuk** [japgolly/scalajs-benchmark#95]
https://github.com/japgolly/scalajs-benchmark/blob/26a88811a587056d88949ffed78899a60faddbfe/benchmark/src/main/scala/japgolly/scalajs/benchmark/engine/TimeUtil.scala#L39-L40

The 3600000 divisor should be used instead of 3660000.

**Comment by japgolly** [comment]
OMG

Thanks @plokhotnyuk . I was literally just about to do a release :o
